/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RootRouteImport } from './routes/_root/route'
import { Route as IndexImport } from './routes/index'
import { Route as AuthLoginImport } from './routes/_auth/login'
import { Route as RootTenantsRouteImport } from './routes/_root/tenants/route'
import { Route as RootStationsRouteImport } from './routes/_root/stations/route'
import { Route as RootDashboardRouteImport } from './routes/_root/dashboard/route'
import { Route as RootUsersIndexImport } from './routes/_root/users/index'
import { Route as RootTenantsIndexImport } from './routes/_root/tenants/index'
import { Route as RootStationsIndexImport } from './routes/_root/stations/index'
import { Route as RootProfileIndexImport } from './routes/_root/profile/index'
import { Route as RootOrganizationIndexImport } from './routes/_root/organization/index'
import { Route as RootMonitoringIndexImport } from './routes/_root/monitoring/index'
import { Route as RootDashboardIndexImport } from './routes/_root/dashboard/index'
import { Route as RootConfigurationIndexImport } from './routes/_root/configuration/index'
import { Route as RootAuditLogsIndexImport } from './routes/_root/audit-logs/index'
import { Route as RootTenantsAddTenantImport } from './routes/_root/tenants/add-tenant'
import { Route as RootStationsCreateImport } from './routes/_root/stations/create'
import { Route as RootDashboardMapImport } from './routes/_root/dashboard/map'
import { Route as RootDashboardDataAnalysisImport } from './routes/_root/dashboard/data-analysis'
import { Route as RootStationsCertificatesRouteImport } from './routes/_root/stations/certificates/route'
import { Route as RootStationsCertificatesIndexImport } from './routes/_root/stations/certificates/index'
import { Route as RootStationsCertificatesRootImport } from './routes/_root/stations/certificates/root'

// Create/Update Routes

const RootRouteRoute = RootRouteImport.update({
  id: '/_root',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const RootTenantsRouteRoute = RootTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootStationsRouteRoute = RootStationsRouteImport.update({
  id: '/stations',
  path: '/stations',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootDashboardRouteRoute = RootDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootUsersIndexRoute = RootUsersIndexImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootTenantsIndexRoute = RootTenantsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootTenantsRouteRoute,
} as any)

const RootStationsIndexRoute = RootStationsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootStationsRouteRoute,
} as any)

const RootProfileIndexRoute = RootProfileIndexImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootOrganizationIndexRoute = RootOrganizationIndexImport.update({
  id: '/organization/',
  path: '/organization/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootMonitoringIndexRoute = RootMonitoringIndexImport.update({
  id: '/monitoring/',
  path: '/monitoring/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootDashboardIndexRoute = RootDashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RootDashboardRouteRoute,
} as any)

const RootConfigurationIndexRoute = RootConfigurationIndexImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootAuditLogsIndexRoute = RootAuditLogsIndexImport.update({
  id: '/audit-logs/',
  path: '/audit-logs/',
  getParentRoute: () => RootRouteRoute,
} as any)

const RootTenantsAddTenantRoute = RootTenantsAddTenantImport.update({
  id: '/add-tenant',
  path: '/add-tenant',
  getParentRoute: () => RootTenantsRouteRoute,
} as any)

const RootStationsCreateRoute = RootStationsCreateImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => RootStationsRouteRoute,
} as any)

const RootDashboardMapRoute = RootDashboardMapImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => RootDashboardRouteRoute,
} as any)

const RootDashboardDataAnalysisRoute = RootDashboardDataAnalysisImport.update({
  id: '/data-analysis',
  path: '/data-analysis',
  getParentRoute: () => RootDashboardRouteRoute,
} as any)

const RootStationsCertificatesRouteRoute =
  RootStationsCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => RootStationsRouteRoute,
  } as any)

const RootStationsCertificatesIndexRoute =
  RootStationsCertificatesIndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => RootStationsCertificatesRouteRoute,
  } as any)

const RootStationsCertificatesRootRoute =
  RootStationsCertificatesRootImport.update({
    id: '/root',
    path: '/root',
    getParentRoute: () => RootStationsCertificatesRouteRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_root': {
      id: '/_root'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RootRouteImport
      parentRoute: typeof rootRoute
    }
    '/_root/dashboard': {
      id: '/_root/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof RootDashboardRouteImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/stations': {
      id: '/_root/stations'
      path: '/stations'
      fullPath: '/stations'
      preLoaderRoute: typeof RootStationsRouteImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/tenants': {
      id: '/_root/tenants'
      path: '/tenants'
      fullPath: '/tenants'
      preLoaderRoute: typeof RootTenantsRouteImport
      parentRoute: typeof RootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/_root/stations/certificates': {
      id: '/_root/stations/certificates'
      path: '/certificates'
      fullPath: '/stations/certificates'
      preLoaderRoute: typeof RootStationsCertificatesRouteImport
      parentRoute: typeof RootStationsRouteImport
    }
    '/_root/dashboard/data-analysis': {
      id: '/_root/dashboard/data-analysis'
      path: '/data-analysis'
      fullPath: '/dashboard/data-analysis'
      preLoaderRoute: typeof RootDashboardDataAnalysisImport
      parentRoute: typeof RootDashboardRouteImport
    }
    '/_root/dashboard/map': {
      id: '/_root/dashboard/map'
      path: '/map'
      fullPath: '/dashboard/map'
      preLoaderRoute: typeof RootDashboardMapImport
      parentRoute: typeof RootDashboardRouteImport
    }
    '/_root/stations/create': {
      id: '/_root/stations/create'
      path: '/create'
      fullPath: '/stations/create'
      preLoaderRoute: typeof RootStationsCreateImport
      parentRoute: typeof RootStationsRouteImport
    }
    '/_root/tenants/add-tenant': {
      id: '/_root/tenants/add-tenant'
      path: '/add-tenant'
      fullPath: '/tenants/add-tenant'
      preLoaderRoute: typeof RootTenantsAddTenantImport
      parentRoute: typeof RootTenantsRouteImport
    }
    '/_root/audit-logs/': {
      id: '/_root/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof RootAuditLogsIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/configuration/': {
      id: '/_root/configuration/'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof RootConfigurationIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/dashboard/': {
      id: '/_root/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof RootDashboardIndexImport
      parentRoute: typeof RootDashboardRouteImport
    }
    '/_root/monitoring/': {
      id: '/_root/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring'
      preLoaderRoute: typeof RootMonitoringIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/organization/': {
      id: '/_root/organization/'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof RootOrganizationIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/profile/': {
      id: '/_root/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof RootProfileIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/stations/': {
      id: '/_root/stations/'
      path: '/'
      fullPath: '/stations/'
      preLoaderRoute: typeof RootStationsIndexImport
      parentRoute: typeof RootStationsRouteImport
    }
    '/_root/tenants/': {
      id: '/_root/tenants/'
      path: '/'
      fullPath: '/tenants/'
      preLoaderRoute: typeof RootTenantsIndexImport
      parentRoute: typeof RootTenantsRouteImport
    }
    '/_root/users/': {
      id: '/_root/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof RootUsersIndexImport
      parentRoute: typeof RootRouteImport
    }
    '/_root/stations/certificates/root': {
      id: '/_root/stations/certificates/root'
      path: '/root'
      fullPath: '/stations/certificates/root'
      preLoaderRoute: typeof RootStationsCertificatesRootImport
      parentRoute: typeof RootStationsCertificatesRouteImport
    }
    '/_root/stations/certificates/': {
      id: '/_root/stations/certificates/'
      path: '/'
      fullPath: '/stations/certificates/'
      preLoaderRoute: typeof RootStationsCertificatesIndexImport
      parentRoute: typeof RootStationsCertificatesRouteImport
    }
  }
}

// Create and export the route tree

interface RootDashboardRouteRouteChildren {
  RootDashboardDataAnalysisRoute: typeof RootDashboardDataAnalysisRoute
  RootDashboardMapRoute: typeof RootDashboardMapRoute
  RootDashboardIndexRoute: typeof RootDashboardIndexRoute
}

const RootDashboardRouteRouteChildren: RootDashboardRouteRouteChildren = {
  RootDashboardDataAnalysisRoute: RootDashboardDataAnalysisRoute,
  RootDashboardMapRoute: RootDashboardMapRoute,
  RootDashboardIndexRoute: RootDashboardIndexRoute,
}

const RootDashboardRouteRouteWithChildren =
  RootDashboardRouteRoute._addFileChildren(RootDashboardRouteRouteChildren)

interface RootStationsCertificatesRouteRouteChildren {
  RootStationsCertificatesRootRoute: typeof RootStationsCertificatesRootRoute
  RootStationsCertificatesIndexRoute: typeof RootStationsCertificatesIndexRoute
}

const RootStationsCertificatesRouteRouteChildren: RootStationsCertificatesRouteRouteChildren =
  {
    RootStationsCertificatesRootRoute: RootStationsCertificatesRootRoute,
    RootStationsCertificatesIndexRoute: RootStationsCertificatesIndexRoute,
  }

const RootStationsCertificatesRouteRouteWithChildren =
  RootStationsCertificatesRouteRoute._addFileChildren(
    RootStationsCertificatesRouteRouteChildren,
  )

interface RootStationsRouteRouteChildren {
  RootStationsCertificatesRouteRoute: typeof RootStationsCertificatesRouteRouteWithChildren
  RootStationsCreateRoute: typeof RootStationsCreateRoute
  RootStationsIndexRoute: typeof RootStationsIndexRoute
}

const RootStationsRouteRouteChildren: RootStationsRouteRouteChildren = {
  RootStationsCertificatesRouteRoute:
    RootStationsCertificatesRouteRouteWithChildren,
  RootStationsCreateRoute: RootStationsCreateRoute,
  RootStationsIndexRoute: RootStationsIndexRoute,
}

const RootStationsRouteRouteWithChildren =
  RootStationsRouteRoute._addFileChildren(RootStationsRouteRouteChildren)

interface RootTenantsRouteRouteChildren {
  RootTenantsAddTenantRoute: typeof RootTenantsAddTenantRoute
  RootTenantsIndexRoute: typeof RootTenantsIndexRoute
}

const RootTenantsRouteRouteChildren: RootTenantsRouteRouteChildren = {
  RootTenantsAddTenantRoute: RootTenantsAddTenantRoute,
  RootTenantsIndexRoute: RootTenantsIndexRoute,
}

const RootTenantsRouteRouteWithChildren =
  RootTenantsRouteRoute._addFileChildren(RootTenantsRouteRouteChildren)

interface RootRouteRouteChildren {
  RootDashboardRouteRoute: typeof RootDashboardRouteRouteWithChildren
  RootStationsRouteRoute: typeof RootStationsRouteRouteWithChildren
  RootTenantsRouteRoute: typeof RootTenantsRouteRouteWithChildren
  RootAuditLogsIndexRoute: typeof RootAuditLogsIndexRoute
  RootConfigurationIndexRoute: typeof RootConfigurationIndexRoute
  RootMonitoringIndexRoute: typeof RootMonitoringIndexRoute
  RootOrganizationIndexRoute: typeof RootOrganizationIndexRoute
  RootProfileIndexRoute: typeof RootProfileIndexRoute
  RootUsersIndexRoute: typeof RootUsersIndexRoute
}

const RootRouteRouteChildren: RootRouteRouteChildren = {
  RootDashboardRouteRoute: RootDashboardRouteRouteWithChildren,
  RootStationsRouteRoute: RootStationsRouteRouteWithChildren,
  RootTenantsRouteRoute: RootTenantsRouteRouteWithChildren,
  RootAuditLogsIndexRoute: RootAuditLogsIndexRoute,
  RootConfigurationIndexRoute: RootConfigurationIndexRoute,
  RootMonitoringIndexRoute: RootMonitoringIndexRoute,
  RootOrganizationIndexRoute: RootOrganizationIndexRoute,
  RootProfileIndexRoute: RootProfileIndexRoute,
  RootUsersIndexRoute: RootUsersIndexRoute,
}

const RootRouteRouteWithChildren = RootRouteRoute._addFileChildren(
  RootRouteRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof RootRouteRouteWithChildren
  '/dashboard': typeof RootDashboardRouteRouteWithChildren
  '/stations': typeof RootStationsRouteRouteWithChildren
  '/tenants': typeof RootTenantsRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/stations/certificates': typeof RootStationsCertificatesRouteRouteWithChildren
  '/dashboard/data-analysis': typeof RootDashboardDataAnalysisRoute
  '/dashboard/map': typeof RootDashboardMapRoute
  '/stations/create': typeof RootStationsCreateRoute
  '/tenants/add-tenant': typeof RootTenantsAddTenantRoute
  '/audit-logs': typeof RootAuditLogsIndexRoute
  '/configuration': typeof RootConfigurationIndexRoute
  '/dashboard/': typeof RootDashboardIndexRoute
  '/monitoring': typeof RootMonitoringIndexRoute
  '/organization': typeof RootOrganizationIndexRoute
  '/profile': typeof RootProfileIndexRoute
  '/stations/': typeof RootStationsIndexRoute
  '/tenants/': typeof RootTenantsIndexRoute
  '/users': typeof RootUsersIndexRoute
  '/stations/certificates/root': typeof RootStationsCertificatesRootRoute
  '/stations/certificates/': typeof RootStationsCertificatesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof RootRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/dashboard/data-analysis': typeof RootDashboardDataAnalysisRoute
  '/dashboard/map': typeof RootDashboardMapRoute
  '/stations/create': typeof RootStationsCreateRoute
  '/tenants/add-tenant': typeof RootTenantsAddTenantRoute
  '/audit-logs': typeof RootAuditLogsIndexRoute
  '/configuration': typeof RootConfigurationIndexRoute
  '/dashboard': typeof RootDashboardIndexRoute
  '/monitoring': typeof RootMonitoringIndexRoute
  '/organization': typeof RootOrganizationIndexRoute
  '/profile': typeof RootProfileIndexRoute
  '/stations': typeof RootStationsIndexRoute
  '/tenants': typeof RootTenantsIndexRoute
  '/users': typeof RootUsersIndexRoute
  '/stations/certificates/root': typeof RootStationsCertificatesRootRoute
  '/stations/certificates': typeof RootStationsCertificatesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_root': typeof RootRouteRouteWithChildren
  '/_root/dashboard': typeof RootDashboardRouteRouteWithChildren
  '/_root/stations': typeof RootStationsRouteRouteWithChildren
  '/_root/tenants': typeof RootTenantsRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_root/stations/certificates': typeof RootStationsCertificatesRouteRouteWithChildren
  '/_root/dashboard/data-analysis': typeof RootDashboardDataAnalysisRoute
  '/_root/dashboard/map': typeof RootDashboardMapRoute
  '/_root/stations/create': typeof RootStationsCreateRoute
  '/_root/tenants/add-tenant': typeof RootTenantsAddTenantRoute
  '/_root/audit-logs/': typeof RootAuditLogsIndexRoute
  '/_root/configuration/': typeof RootConfigurationIndexRoute
  '/_root/dashboard/': typeof RootDashboardIndexRoute
  '/_root/monitoring/': typeof RootMonitoringIndexRoute
  '/_root/organization/': typeof RootOrganizationIndexRoute
  '/_root/profile/': typeof RootProfileIndexRoute
  '/_root/stations/': typeof RootStationsIndexRoute
  '/_root/tenants/': typeof RootTenantsIndexRoute
  '/_root/users/': typeof RootUsersIndexRoute
  '/_root/stations/certificates/root': typeof RootStationsCertificatesRootRoute
  '/_root/stations/certificates/': typeof RootStationsCertificatesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/dashboard'
    | '/stations'
    | '/tenants'
    | '/login'
    | '/stations/certificates'
    | '/dashboard/data-analysis'
    | '/dashboard/map'
    | '/stations/create'
    | '/tenants/add-tenant'
    | '/audit-logs'
    | '/configuration'
    | '/dashboard/'
    | '/monitoring'
    | '/organization'
    | '/profile'
    | '/stations/'
    | '/tenants/'
    | '/users'
    | '/stations/certificates/root'
    | '/stations/certificates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/dashboard/data-analysis'
    | '/dashboard/map'
    | '/stations/create'
    | '/tenants/add-tenant'
    | '/audit-logs'
    | '/configuration'
    | '/dashboard'
    | '/monitoring'
    | '/organization'
    | '/profile'
    | '/stations'
    | '/tenants'
    | '/users'
    | '/stations/certificates/root'
    | '/stations/certificates'
  id:
    | '__root__'
    | '/'
    | '/_root'
    | '/_root/dashboard'
    | '/_root/stations'
    | '/_root/tenants'
    | '/_auth/login'
    | '/_root/stations/certificates'
    | '/_root/dashboard/data-analysis'
    | '/_root/dashboard/map'
    | '/_root/stations/create'
    | '/_root/tenants/add-tenant'
    | '/_root/audit-logs/'
    | '/_root/configuration/'
    | '/_root/dashboard/'
    | '/_root/monitoring/'
    | '/_root/organization/'
    | '/_root/profile/'
    | '/_root/stations/'
    | '/_root/tenants/'
    | '/_root/users/'
    | '/_root/stations/certificates/root'
    | '/_root/stations/certificates/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RootRouteRoute: typeof RootRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RootRouteRoute: RootRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_root",
        "/_auth/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_root": {
      "filePath": "_root/route.tsx",
      "children": [
        "/_root/dashboard",
        "/_root/stations",
        "/_root/tenants",
        "/_root/audit-logs/",
        "/_root/configuration/",
        "/_root/monitoring/",
        "/_root/organization/",
        "/_root/profile/",
        "/_root/users/"
      ]
    },
    "/_root/dashboard": {
      "filePath": "_root/dashboard/route.tsx",
      "parent": "/_root",
      "children": [
        "/_root/dashboard/data-analysis",
        "/_root/dashboard/map",
        "/_root/dashboard/"
      ]
    },
    "/_root/stations": {
      "filePath": "_root/stations/route.tsx",
      "parent": "/_root",
      "children": [
        "/_root/stations/certificates",
        "/_root/stations/create",
        "/_root/stations/"
      ]
    },
    "/_root/tenants": {
      "filePath": "_root/tenants/route.tsx",
      "parent": "/_root",
      "children": [
        "/_root/tenants/add-tenant",
        "/_root/tenants/"
      ]
    },
    "/_auth/login": {
      "filePath": "_auth/login.tsx"
    },
    "/_root/stations/certificates": {
      "filePath": "_root/stations/certificates/route.tsx",
      "parent": "/_root/stations",
      "children": [
        "/_root/stations/certificates/root",
        "/_root/stations/certificates/"
      ]
    },
    "/_root/dashboard/data-analysis": {
      "filePath": "_root/dashboard/data-analysis.tsx",
      "parent": "/_root/dashboard"
    },
    "/_root/dashboard/map": {
      "filePath": "_root/dashboard/map.tsx",
      "parent": "/_root/dashboard"
    },
    "/_root/stations/create": {
      "filePath": "_root/stations/create.tsx",
      "parent": "/_root/stations"
    },
    "/_root/tenants/add-tenant": {
      "filePath": "_root/tenants/add-tenant.tsx",
      "parent": "/_root/tenants"
    },
    "/_root/audit-logs/": {
      "filePath": "_root/audit-logs/index.tsx",
      "parent": "/_root"
    },
    "/_root/configuration/": {
      "filePath": "_root/configuration/index.tsx",
      "parent": "/_root"
    },
    "/_root/dashboard/": {
      "filePath": "_root/dashboard/index.tsx",
      "parent": "/_root/dashboard"
    },
    "/_root/monitoring/": {
      "filePath": "_root/monitoring/index.tsx",
      "parent": "/_root"
    },
    "/_root/organization/": {
      "filePath": "_root/organization/index.tsx",
      "parent": "/_root"
    },
    "/_root/profile/": {
      "filePath": "_root/profile/index.tsx",
      "parent": "/_root"
    },
    "/_root/stations/": {
      "filePath": "_root/stations/index.tsx",
      "parent": "/_root/stations"
    },
    "/_root/tenants/": {
      "filePath": "_root/tenants/index.tsx",
      "parent": "/_root/tenants"
    },
    "/_root/users/": {
      "filePath": "_root/users/index.tsx",
      "parent": "/_root"
    },
    "/_root/stations/certificates/root": {
      "filePath": "_root/stations/certificates/root.tsx",
      "parent": "/_root/stations/certificates"
    },
    "/_root/stations/certificates/": {
      "filePath": "_root/stations/certificates/index.tsx",
      "parent": "/_root/stations/certificates"
    }
  }
}
ROUTE_MANIFEST_END */
